# general
set -g status on
set -g pane-base-index 1
set -g base-index 1
set -g set-titles on
set -g default-terminal "screen-256color"
set-option -g set-titles-string '#{pane_current_command}'
set-option -g history-limit 10000
set-option -g status-position top
set-option -g renumber-windows on
set-window-option -g monitor-activity off
set -g default-terminal "tmux"

# mouse
set -g mouse on
bind -T root WheelUpPane   if-shell -F -t = "#{alternate_on}" "send-keys -M" "select-pane -t =; copy-mode -e; send-keys -M"
bind -T root WheelDownPane if-shell -F -t = "#{alternate_on}" "send-keys -M" "select-pane -t =; send-keys -M"

# vim mode
setw -g mode-keys vi

# prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# activity
setw -g monitor-activity on
set-option -g visual-activity off

# split
set-option -g pane-active-border-fg colour234
set-option -g pane-active-border-bg default
set-option -g pane-border-fg colour234
set-option -g pane-border-bg default

# statusbar
set -g status-left ''
set -g status-right ''
set -g status-bg default
setw -g window-status-format '#[fg=grey,bg=black] #I#[fg=grey,bg=black] #W'
setw -g window-status-current-format '#[fg=white,bg=blue] #I#[fg=white,bg=blue] #W'
# status colors
#set -g message-command-style '#[fg=grey,bg=black]'
#set -g message-command-style 'fg=red,bold,underscore'
set -g message-style 'fg=white,bg=blue'

# previous pane
bind -r i select-pane -t:.-
